version: "3"
services:
  webdav:
    image: bytemark/webdav
    hostname: web
    restart: always
    environment:
      AUTH_TYPE: Digest
      USERNAME: frodo
      PASSWORD: bolson
    volumes:
      - /srv/dav:/var/lib/dav
    depends_on:
        - proxy
  proxy:
      image: nginx
      ports:
        - '80:80'
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
